apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.labels.app }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
