apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
data:
  MYSQL_HOST: "{{ .Values.mysql.host }}"
  MYSQL_USER: "{{ .Values.mysql.user }}"
  MYSQL_DB: "{{ .Values.mysql.database }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      version: {{ .Values.labels.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        version: {{ .Values.labels.version }}
        env: {{ .Values.labels.env }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.container.port }}
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MYSQL_USER
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MYSQL_DB
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.container.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
