namespace: staging
labels:
  app: mysql
  env: staging
  version: v1

replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

container:
  name: mysql
  port: 3306

mysql:
  rootPassword: root
  database: python_crud
  user: appuser
  password: apppassword

service:
  name: mysql-service
  type: ClusterIP
  port: 3306

pvc:
  name: mysql-pvc-staging
  storage: 1Gi

deployment:
  name: mysql-deployment
